### ISSUE TITLE
feat(useForm): Form state management and rule validation

### ISSUE THREAD

**Issue by LittleSound** [vueuse/vueuse#1590]
### Clear and concise description of the problem

I want to develop a `useForm` function to simplify form manipulation

Seek everyone's opinion

### Suggested solution

The current concept of the `useForm` function
#### Code
```vue
<script lang="js" setup>
const { form, error, reset, onSubmit } = useForm({
  // Initial form value
  form: () => ({
    age: '',
  }),
  // Verification rules
  rule: () => ({
    age: [
      /* required */ val => !!val || t('required'), // i18n support
      /* number */ val => !Number.isNaN(val) || 'Expected number',
      /* length */ val => val.length < 3 || 'Length needs to be less than 3',
    ],
  }),
})

function mySubmit() { /** Code */ }
</script>
<template>
  <h3>Please enter your age</h3>

  <form @submit.prevent="onSubmit(mySubmit)">
    <label>
      <input v-model="form.age" type="text">
      <p>{{ error.age }}</p>
    </label>

    <button type="submit">
      Submit
    </button>

    <button @click="reset">
      reset
    </button>
  </form>
</template>
```

#### TODO

- args
  - A function that returns the initial value of the form
  - A function that returns the validation rules
- return
  - func
    - Manually trigger form validation
    - reset form error
      - Support clearing specified fields
    - Submit (automatically verify rules before submitting)
    - reset form data (restore default)
  - reactive
    - form object
    - error message object
    - whether the value is modified

### Mind Mapping:
![image](https://user-images.githubusercontent.com/19204772/167990469-80a23593-2c2d-4ab0-9603-275eeed68544.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SnowingFox** [comment]
nice idea

**Comment by userquin** [comment]
@LittleSound have you check `yup`?

**Comment by LittleSound** [comment]
> @LittleSound have you check `yup`?

I didn't know `yup` before, what do you want to say?

**Comment by userquin** [comment]
> > @LittleSound have you check `yup`?
> 
> I didn't know `yup` before, what do you want to say?

I mean, using it for the rules, for example `vee-validate v4` is using it, maybe for this is out of scope

**Comment by LittleSound** [comment]
> > > @LittleSound have you check `yup`?
> > 
> > 
> > I didn't know `yup` before, what do you want to say?
> 
> I mean, using it for the rules, for example `vee-validate v4` is using it, maybe for this is out of scope

I have checked the [source code associated and  related to `yup` from `vee-validate`](https://github.com/logaretm/vee-validate/blob/a5b36f63ce6cec432d6974346760ea41307d66f4/packages/vee-validate/src/validate.ts#L134), somehow I find out that there are two things that needs to be resolve and discuss as follows:

1. `yup` requires the validation to be in async in order to work.
2. As the vueuse requires and declares, `@vueuse/core` won't include any third party dependencies, however, in order to have better Typescript support for `yup` validation, include `yup` as a dependency for `useForm` in `@vueuse/core` which would violate the pre-requirements.

**Comment by LittleSound** [comment]
I created a separate repository to develop this issue, it's an experiment 🧪

https://github.com/LittleSound/slimeform

**Comment by LittleSound** [comment]
Hi @userquin 👋. I've implemented the ability to [use Yup for rules](https://github.com/LittleSound/slimeform#integrations) in [SlimeForm](https://github.com/LittleSound/slimeform), maybe you can try it~

This draft is the predecessor of [SlimeForm](https://github.com/LittleSound/slimeform) and now I am continuing development in [SlimeForm](https://github.com/LittleSound/slimeform).
