### ISSUE TITLE
useMagicKeys triggers only once if meta key is pressed

### ISSUE THREAD

**Issue by Destiner** [vueuse/vueuse#2298]
### Describe the bug

Pressing a key and then releasing it while the `Meta` key is pressed will not remove that key from the list of currently pressed keys.

One way to reproduce is to open [useMagicKeys demo](https://vueuse.org/core/usemagickeys/) and:
1) press `CMD` (meta key)
2) press `b` (while holding the meta key)
3) release `b` (while holding the meta key)

You will see that the `b` is still presented as "pressed" key

Compare this with the `CTRL` key behavior. Pressing `CTRL`, then pressing `b`, the releasing `b` will remove the `b` key from the list of pressed keys.

This will in turn affect combinations like `meta_b`. If you press and release `b` multiple times while holding `CMD`, the `meta_b` value will update only once. In contrast, `ctrl_b` will update each time you press `b` (see reproduction demo).

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ftzvbd?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 75.77 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6
  npmPackages:
    @vueuse/core: ^9.3.0 => 9.3.0 
    vue: 3.2.33 => 3.2.33
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Thinkro** [comment]
Thought i did something wrong, but can confirm this happens to me also.

**Comment by Blackfaded** [comment]
Had the same issue times ago.
Had to implement a custom solution that worked for me:

```ts
import { ref, onUnmounted, onMounted, Ref, nextTick } from 'vue';

import { KeyEnum } from '@/libs/shared/enums/keys';

type RefType = Record<KeyEnum, Ref<boolean>>;

export const useKeys = () => {
  // @ts-ignore
  const refs: RefType = {};

  const keydown = (event: KeyboardEvent) => {
    const pressedKey = event.key as KeyEnum;
    if (pressedKey in refs) {
      refs[pressedKey].value = true;

      // needed because of command key bug:
      // https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key
      if (refs['Meta']?.value && pressedKey !== 'Meta' && pressedKey !== 'Shift') {
        nextTick(() => {
          refs[pressedKey].value = false;
        });
      }
    }
  };

  const keyup = (event: KeyboardEvent) => {
    const pressedKey = event.key as KeyEnum;
    if (pressedKey in refs) {
      refs[pressedKey].value = false;
    }
  };

  const attachListeners = () => {
    document.addEventListener('keydown', keydown);
    document.addEventListener('keyup', keyup);
  };

  const detachListeners = () => {
    document.removeEventListener('keydown', keydown);
    document.removeEventListener('keyup', keyup);
  };

  onMounted(() => {
    attachListeners();
  });

  onUnmounted(() => {
    detachListeners();
  });

  const handler: ProxyHandler<RefType> = {
    get(target: RefType, prop: KeyEnum, receiver: any) {
      if (!(prop in refs)) {
        refs[prop] = ref(false);
      }
      return Reflect.get(target, prop, receiver);
    },
  };

  const proxy = new Proxy(refs, handler);

  return proxy;
};
```

There is also the Stack Overflow issue linked which describes the problem. Maybe this could be adopted to `vueuse`

**Comment by lainbo** [comment]
It also appears here, Meta key will cause the interaction of the operating system, resulting in `keyup`, `current` still has the key pressed together with Meta, even now the key has been released

**Comment by Thinkro** [comment]
Seems there's been multiple attempts to fix it? https://github.com/vueuse/vueuse/pull/1312

**Comment by Thinkro** [comment]
All of these issues/pull requests
https://github.com/vueuse/vueuse/issues/2298
https://github.com/vueuse/vueuse/pull/1312
https://github.com/vueuse/vueuse/pull/946
https://github.com/vueuse/vueuse/issues/915
https://github.com/vueuse/vueuse/issues/491

Are related to bugs with metakey.
