### ISSUE TITLE
useMeta to modify documents <meta>

### ISSUE THREAD

**Issue by d-koppenhagen** [vueuse/vueuse#2878]
### Clear and concise description of the problem

As a developer using VueUse I want be able to modify the documents `<meta>` tag for a single page. This allows me to set individual meta tags such as `<meta name="referrer" …>`.

I can also contribute.

### Suggested solution

The implementation could be similar to `useTitle` like this:

```
const meta = useMeta({ name: 'referrer', content: 'origin' })
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
