### ISSUE TITLE
In iOS Safari, useWindowSize can't correct detect window.innerWith when dynamic change head meta viewport content

### ISSUE THREAD

**Issue by xuyimingwork** [vueuse/vueuse#3409]
### Describe the bug

When dynamic change `head meta[name="viewport"]` element's content attribute value using js, in iOS Safari, the useWindowSize value not change. 
It seems that iOS Safari not trigger resize event, compare to Android Chrome, cause useWindowSize's width not the same as window.innerWith.
Not sure this should be solved in vueuse or is a iOS Safari bug that not part of vueuse.

Reproduction: 
code: https://codesandbox.io/s/vant-4-issue-template-forked-p6yn9w?file=/src/App.vue
use iOS device visit & click update viewport: https://p6yn9w.csb.app/

### Reproduction

https://codesandbox.io/s/vant-4-issue-template-forked-p6yn9w?file=/src/App.vue

### System Info

```Shell
no need for pc system info
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
