### ISSUE TITLE
watchEffect with a callback(without tracking)

### ISSUE THREAD

**Issue by qzsiniong** [vueuse/vueuse#4075]
### Clear and concise description of the problem

```ts
const same = ref(true); // is name2 must same of name1
const name1 = ref('1');
const name2 = ref('2'); // name2 not same of name1, although the same is true（because this  is from DB）

let first = true;
watchEffect(()=>{
  const _first = first;
  first = false;
  if (same.value) {
    const value1 = name1.value;

    if (!_first) {// not run when the first time
      name2.value = value1;
    }
  }
});
```

----
simple with the following

```ts
const same = ref(true); // is name2 must same of name1
const name1 = ref('1');
const name2 = ref('2'); // name2 not same of name1, although the same is true（because this  is from DB）


watchXXX(()=>{
  // tracking
  const isSame = same.value;
  const value1 = name1.value;

  return () => {
    if (isSame) {
      name2.value = value1;
    }
  }
},{ 
  immediate: false // not run the callback when first
 });
```

### Suggested solution

```ts
// It like watchEffect
function watchXXX(effect, options) {
  let count = 0;
  return watchEffect((cleanupFn) => {
    const _count = count++;

    const doUnTrack = effect(cleanupFn);

    const immediate = options && options.immediate;
    if (immediate || _count>0) {
      withoutTracking(() => {
        doUnTrack(_count);
      });
    }
  }, options);
}

function withoutTracking(fn: () => void) {
  pauseTracking();
  try {
    fn();
  } catch (e) {
    throw e;
  } finally {
    resetTracking();
  }
}

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
